version: "3"
services:
  
  backend:
    build: ./payment_module
    env_file: ./payment_module/dev.env
    networks:
      - solepay-network
  
  frontend:
    build: .
    environment:
      SERVER_NAME: http://ip172-19-0-42-cgldncqe69v000a5gmj0-80.direct.labs.play-with-docker.com/
    ports:
      - "80:80"
    networks:
      - solepay-network

networks:
  solepay-network:
    driver: bridge