version: "3.9"
services:
  frontend:
    depends_on:
      - backend
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_NAME: http://ip172-18-0-70-cgkm1n81k7jg00dlabj0-80.direct.labs.play-with-docker.com
    ports:
      - "80:80"
  
  backend:
    build:
      context: ./payment_module
      dockerfile: Dockerfile
    env_file:
      - ./payment_module/dev.env
